apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: forex-app-service-frontend
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
    rules:
        - host: forex-service.{url_host}
          http:
              paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: forex-app-service-frontend
                    port: 
                      number: 80
    tls:
       - secretName: forex-tls
         hosts:
         - forex-service.{url_host}
---
apiVersion: v1
kind: Service
metadata:
  name: forex-app-service-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: forex-app-service-frontend
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: forex-app-service-frontend
spec:
  selector:
    matchLabels:
      app: forex-app-service-frontend
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: forex-app-service-frontend
    spec:
      containers:
      - name: forex-app-service
        image: emandere/forex-app-service-{platform}:{buildId}
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "frontend"
        ports:
        - containerPort: 80
        volumeMounts:
          - name: secrets
            mountPath: "/app/secrets"
            readOnly: true
      nodeSelector:
        platform: {platform}
      volumes:
        - name: secrets
          secret:
            secretName: fxaccount
