FROM  mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app
COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet build
RUN dotnet publish -c Release -r linux-arm64 -o out --self-contained true /p:PublishTrimmed=true

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:6.0.0-buster-slim-arm64v8
COPY openssl.cnf /etc/ssl/openssl.cnf
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "forex-app-service.dll"]