apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: basic-ingress
spec:
    rules:
        - http:
            paths:
            - path: /service
              backend:
                serviceName: forex-app-service
                servicePort: 80